name: "Release"

on:
  release:
    types:
      - "published"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      discussions: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/askoheat"
          zip askoheat.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: "softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b" # v3.0.1
        with:
          files: ${{ github.workspace }}/custom_components/askoheat/askoheat.zip
